### ISSUE TITLE
connect polling page to Google Civic API

### ISSUE THREAD

**Issue by B-Dionysus** [B-Dionysus/project1-Election#11]

**Comment by aaray12** [comment]
@B-Dionysus @sarahlcox 
Their information for hours comes up like this: 
<img width="1119" alt="Screen Shot 2020-10-07 at 2 00 53 PM" src="https://user-images.githubusercontent.com/69473014/95375664-893c7980-08a5-11eb-9635-3ce2892d3ecf.png">

Since the hours are the same for each polling location(8:30-7pm monday-friday. 9-5 saturday-sunday) how do you feel about just listing the start date and end date from the api with created variables with the hours listed above(meaning not pulled from the API, sry I dont know how to word that exactly).
